<Project Sdk="Godot.NET.Sdk/4.7.1">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <!-- Required for Godot 4 -->
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <!-- Disable NativeAOT, it breaks Windows exports. -->
    <PublishAOT>false</PublishAOT>
    <LangVersion>12.0</LangVersion>
    <!-- Enforce nullable warnings -->
    <Nullable>enable</Nullable>
    <!-- Disable invalid/incompatible GodotSharp version warnings -->
    <NoWarn>NU1605</NoWarn>
    <RootNamespace>energyshot</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <!-- Root the assemblies to avoid trimming. -->
    <TrimmerRootAssembly Include="GodotSharp" />
    <TrimmerRootAssembly Include="$(TargetName)" />
  </ItemGroup>
  <ItemGroup>
    <!-- Required for GdUnit4 -->
    <PackageReference Include="gdUnit4.api" Version="5.1.0-rc1" />
    <!-- Required for GdUnit4 IDE support (Rider, Visual Studio, Visual Studio Code) -->
    <PackageReference Include="gdUnit4.test.adapter" Version="3.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
  </ItemGroup>
</Project>
